# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 04:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pidfaesa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_nome', models.CharField(max_length=400, verbose_name='Nome')),
                ('dt_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('ds_telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('ds_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('dthr_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data fim')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_nome', models.CharField(max_length=400, verbose_name='Nome')),
                ('ds_descricao', models.TextField(max_length=4000, verbose_name='Descricao')),
                ('ds_local', models.CharField(max_length=300, verbose_name='Local')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_descricao', models.CharField(max_length=500, verbose_name='Descricao')),
                ('no_ordem', models.PositiveSmallIntegerField(verbose_name='Ordem')),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_titulo', models.CharField(max_length=300, verbose_name='Titulo')),
                ('ds_descricao', models.TextField(max_length=500, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_descricao', models.CharField(max_length=300, verbose_name='Descricao')),
                ('no_ordem', models.PositiveSmallIntegerField(verbose_name='Ordem')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pidfaesa.Pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_nome', models.CharField(max_length=400, verbose_name='Nome')),
                ('ds_descricao', models.TextField(max_length=4000, verbose_name='Descricao')),
                ('ds_periodo', models.CharField(choices=[('1', 'Manha'), ('2', 'Tarde'), ('3', 'Noite')], max_length=1, verbose_name='Periodo')),
                ('dt_ini', models.DateField(default=datetime.date.today, verbose_name='Data de inicio')),
                ('dt_fim', models.DateField(default=pidfaesa.models.get_60days_from_now, verbose_name='Data de fim')),
                ('no_carga_horaria', models.PositiveSmallIntegerField(verbose_name='Carga horaria')),
                ('no_vagas', models.PositiveSmallIntegerField(verbose_name='Quantidade de vagas')),
                ('no_vagas_extras', models.PositiveSmallIntegerField(verbose_name='Quantidade de vagas extras')),
                ('dthr_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criacao')),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pidfaesa.Questionario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pidfaesa.Questionario'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pidfaesa.Turma'),
        ),
    ]
