# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 05:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='dthr_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 13, 5, 2, 46, 546000, tzinfo=utc), verbose_name='Data de criacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='ds_descricao',
            field=models.TextField(max_length=2000, verbose_name='Descricao'),
        ),
    ]
