# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 15:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0002_auto_20160913_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='dthr_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 13, 15, 4, 34, 468000, tzinfo=utc), verbose_name='Data de criacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='dthr_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 13, 15, 4, 41, 265000, tzinfo=utc), verbose_name='Data de criacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resposta',
            name='dthr_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 13, 15, 4, 46, 468000, tzinfo=utc), verbose_name='Data de criacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pidfaesa.Curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionario',
            name='ds_descricao',
            field=models.TextField(max_length=600, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='ds_titulo',
            field=models.CharField(max_length=400, verbose_name='Titulo'),
        ),
    ]
