# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0004_auto_20160913_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='turma',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
