# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0005_auto_20160918_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='ds_periodo',
        ),
    ]
