# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0007_auto_20160918_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='questionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pidfaesa.Questionario'),
        ),
    ]
