# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0008_auto_20160918_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='cursovoluntario',
            options={'verbose_name': 'Voluntario - Curso', 'verbose_name_plural': 'Voluntarios - Cursos'},
        ),
        migrations.AlterModelOptions(
            name='escolavoluntario',
            options={'verbose_name': 'Voluntario - Escola', 'verbose_name_plural': 'Voluntarios - Escolas'},
        ),
        migrations.AlterModelOptions(
            name='questionario',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['-pk']},
        ),
    ]
