# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0011_auto_20161013_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaVoluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_presenca', models.DateField(verbose_name='Data da presenca')),
                ('no_hora_aula', models.PositiveSmallIntegerField(verbose_name='Hora aula')),
                ('dthr_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criacao')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pidfaesa.Voluntario')),
            ],
        ),
        migrations.AlterField(
            model_name='presencaaluno',
            name='dt_presenca',
            field=models.DateField(verbose_name='Data da presenca'),
        ),
    ]
