# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0012_auto_20161013_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='no_hora_aula_total',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='no_hora_aula_total',
        ),
    ]
