# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0013_auto_20161013_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_body', models.TextField(max_length=600, verbose_name='Html body')),
                ('dthr_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criacao')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pidfaesa.Turma')),
            ],
        ),
    ]
