# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0014_certificado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='cursovoluntario',
            options={'ordering': ['ds_nome'], 'verbose_name': 'Voluntario - Curso', 'verbose_name_plural': 'Voluntarios - Cursos'},
        ),
        migrations.AlterModelOptions(
            name='escolavoluntario',
            options={'ordering': ['ds_nome'], 'verbose_name': 'Voluntario - Escola', 'verbose_name_plural': 'Voluntarios - Escolas'},
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['no_ordem']},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={'ordering': ['no_ordem']},
        ),
        migrations.AlterModelOptions(
            name='voluntario',
            options={'ordering': ['-pk']},
        ),
    ]
