# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0015_auto_20161026_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alun_resp_perg_ques',
            options={'ordering': ['questionario', 'pergunta', 'resposta', 'aluno'], 'verbose_name': 'Quest/Resp/Perg/Alun', 'verbose_name_plural': 'Questionario/Resposta/Pergunta/Aluno'},
        ),
        migrations.AlterModelOptions(
            name='cursovoluntario',
            options={'ordering': ['pk'], 'verbose_name': 'Voluntario/Curso disponivel', 'verbose_name_plural': 'Voluntarios/Cursos disponiveis'},
        ),
        migrations.AlterModelOptions(
            name='escolavoluntario',
            options={'ordering': ['pk'], 'verbose_name': 'Voluntario/Escola disponivel', 'verbose_name_plural': 'Voluntarios/Escolas disponiveis'},
        ),
        migrations.AlterModelOptions(
            name='presencaaluno',
            options={'ordering': ['dt_presenca', 'aluno'], 'verbose_name': 'Presenca de Aluno', 'verbose_name_plural': 'Presencas de Alunos'},
        ),
        migrations.AlterModelOptions(
            name='presencavoluntario',
            options={'ordering': ['dt_presenca', 'voluntario'], 'verbose_name': 'Presenca de Voluntario', 'verbose_name_plural': 'Presencas de Voluntarios'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='presencaaluno',
            name='is_presente',
            field=models.BooleanField(default=False, verbose_name='Presente'),
        ),
        migrations.AddField(
            model_name='presencavoluntario',
            name='is_presente',
            field=models.BooleanField(default=False, verbose_name='Presente'),
        ),
    ]
