# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0016_auto_20161027_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presencaaluno',
            options={'ordering': ['-dt_presenca', 'aluno'], 'verbose_name': 'Presenca de Aluno', 'verbose_name_plural': 'Presencas de Alunos'},
        ),
        migrations.AlterModelOptions(
            name='presencavoluntario',
            options={'ordering': ['-dt_presenca', 'voluntario'], 'verbose_name': 'Presenca de Voluntario', 'verbose_name_plural': 'Presencas de Voluntarios'},
        ),
    ]
