# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pidfaesa', '0017_auto_20161118_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alun_resp_perg_ques',
            options={'ordering': ['questionario', 'pergunta', 'resposta', 'aluno'], 'verbose_name': 'Quest/Perg/Resp/Alun', 'verbose_name_plural': 'Questionario/Pergunta/Resposta/Aluno'},
        ),
        migrations.AlterModelOptions(
            name='cursovoluntario',
            options={'ordering': ['ds_nome'], 'verbose_name': 'Voluntario/Curso disponivel', 'verbose_name_plural': 'Voluntarios/Cursos disponiveis'},
        ),
        migrations.AlterModelOptions(
            name='escolavoluntario',
            options={'ordering': ['ds_nome'], 'verbose_name': 'Voluntario/Escola disponivel', 'verbose_name_plural': 'Voluntarios/Escolas disponiveis'},
        ),
    ]
